### ISSUE TITLE
error with setup.py

### ISSUE THREAD

**Issue by nhanct** [nylas/make-deb#1]
when i run make-deb without setup.py on current dir.
I got this error:
python: can't open file '/root/dashboard-vtg/setup.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/make-deb", line 16, in <module>
    main()
  File "/usr/local/bin/make-deb", line 11, in main
    debconf.render()
  File "/usr/local/lib/python2.7/dist-packages/make_deb/**init**.py", line 89, in render
    trigger_filename = "%s.triggers" % self.context['name']
KeyError: 'name'

**Comment by systemizer** [comment]
Hey nhanct! 

This was actually fixed in 0.0.3: https://github.com/nylas/make-deb/commit/183c7c598534661bf4646082188da28d35defe4c

Thanks for reporting the issue.
